version: "3.3"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    command:
      poetry run flask run --host=0.0.0.0
    environment:
      FLASK_APP: EasyHigh/main.py
      steam_account_name:
      steam_password:
